### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mnrv-ae** [nicbou/burgeramt-appointments-websockets#11]
Hello again, thanks for quick feedback, the earlier error is definitely fixed. But there is a new one, I tried with the two URLs below:
* https://service.berlin.de/dienstleistung/305244/
* https://otv.verwalt-berlin.de/ams/TerminBuchen

Both with the same result:
```
[2023-04-11 11:23:42] INFO: Getting appointment URL for https://otv.verwalt-berlin.de/ams/TerminBuchen
Traceback (most recent call last):
  File "/usr/local/bin/appointments", line 67, in <module>
    asyncio.run(watch_for_appointments(service_page_url, email, args.id, args.port, args.quiet))
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/appointments/appointments.py", line 171, in watch_for_appointments
    appointments_url = await get_appointments_url(service_page_url, email, script_id)
  File "/usr/local/lib/python3.10/site-packages/appointments/appointments.py", line 51, in get_appointments_url
    return termin_suchen_link['href']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mnrv-ae** [comment]
Well it was posted as 

"It lets you find different types of appointments, not just for the Anmeldung."

so, my bad for the misunderstanding, thanks anyway
